### ISSUE TITLE
BRender 1.3.2 Tracking Issue

### ISSUE THREAD

**Issue by vs49688** [crocguy0688/CrocDE-BRender#7]
# Tracking issue for BRender 1.3.2 update. 

Due to the sheer amount of changes in this version (64-bit support, OpenGL renderer, etc.), the BRender 1.3.2 changes should be merged into here, instead of vice versa. This issue tracks the progress. 

Development is happening in https://github.com/crocguy0688/CrocDE-BRender/pull/6
## tool status

| Tool       | Status |
|------------|--------|
| `3ds2br`   | Done        |
| `dquery`   |  Done      |
| `dripmem`  |  Done      |
| `geoconv`  | Rejected, dosio dependency.       |
| `mkblend`  | Done        |
| `mkfog`    | Done        |
| `mkranges` |  Done      |
| `mkshades` | Done       |
| `modtest`  |  Rejected, dosio dependency.      |
| `paljoin`  |  Done    |
| `testview` |  Rejected, dosio dependency.        |
| `texconv`  | Done       |
| `timetest` | Rejected, dosio dependency.       |
| `trackmem` |  Rejected, too much DOS.      |
| `viewpal`  | Rejected, requires creating screen       |

## fmt Status

| Header    | Source      | Status |
|-----------|-------------|--------|
| `fmt.h`   |             | Done       |
| `fmt_p.h` |             |  Done      |
|           | `load3ds.c` |  Done      |
|           | `load3ds.h` |    Done    |
|           | `loadasc.c` | Done       |
|           | `loadbmp.c` |  Done      |
|           | `loadgif.c` | Done       |
|           | `loadiff.c` |  Done      |
|           | `loadnff.c` |   Done     |
|           | `loadscr.c` | Done   |
|           | `loadtga.c` |  Done      |
|           | `loadvue.c` | Done       |
|           | `savescr.c` |  Done  |

## v1db Status

| Header           | Source            | Status          |
|------------------|-------------------|-----------------|
|                  | `v1db/actsupt.c`  | Done            |
|                  | `v1db/custsupt.c` | Done            |
|                  | `v1db/dbquery.c`  | Done            |
|                  | `v1db/dbsetup.c`  | Done            |
|                  | `v1db/def_mat.c`  | Done            |
|                  | `v1db/def_mdl.c`  | Done            |
|                  | `v1db/def_otab.c` | Done            |
|                  | `v1db/enables.c`  | Done            |
|                  | `v1db/ffhooks.c`  | Done            |
| `v1db/horizon.h` |                   | Done, removed   |
|                  | `v1db/matsupt.c`  | Done            |
|                  | `v1db/modrend.c`  | Done            |
|                  | `v1db/otable.c`   | Done            |
|                  | `v1db/pick.c`     | Done            |
|                  | `v1db/prelight.c` | Done            |
|                  | `v1db/prepmap.c`  | Done            |
|                  | `v1db/prepmatl.c` | Done            |
|                  | `v1db/prepmesh.c` | Done            |
|                  | `v1db/preptab.c`  | Done            |
|                  | `v1db/regsupt.c`  | Done            |
|                  | `v1db/render.c`   | Done            |
| `v1db/v1db.h`    |                   | Done            |
| `v1db/v1db_ip.h` |                   | Done            |
|                  | `v1db/v1dbfile.c` | Done            |
| `v1db/zsmacro.h` |                   | Done, no change |

## fw Status

| Header            | Source           | Status   |
|-------------------|------------------|----------|
|                   | `fw/assocarr.c`  | Done     |
| `fw/blockops.h`   |                  | Done     |
| `fw/brassert.h`   |                  | Done     |
|                   | `fw/brbegin.c`   | Done     |
|                   | `fw/brbhook.c`   | Done     |
| `fw/brddi_p.h`    |                  | Done     |
| `fw/brddi.h`      |                  | Done     |
| `fw/brexcept.h`   |                  | Done     |
| `fw/brhton.h`     |                  | Done     |
| `fw/brimage.h`    |                  | Done     |
| `fw/brlists.h`    | `fw/brlists.c`   | Done     |
|                   | `fw/brqsort.c`   | Done     |
| `fw/brstdlib.h`   |                  | Done     |
|                   | `fw/bswap.c`     | Done     |
| `fw/dataf_p.h`    |                  | Done     |
| `fw/datafile.h`   | `fw/datafile.c`  | Done     |
|                   | `fw/defdiag.c`   | Done     |
|                   | `fw/deffile.c`   | Done     |
|                   | `fw/defmem.c`    | Done     |
| `fw/dev_objs.hpp` |                  | Done     |
|                   | `fw/devlist.c`   | Done     |
|                   | `fw/devquery.c`  | Done     |
|                   | `fw/devsetup.c`  | Done     |
|                   | `fw/diag.c`      | Done     |
|                   | `fw/error.c`     | Done     |
|                   | `fw/file.c`      | Done     |
|                   | `fw/foo.c`       | Excluded |
| `fw/formats.h`    |                  | Done     |
| `fw/fw.h`         |                  | Done     |
| `fw/fw_ip.h`      |                  | Done     |
| `fw/fwimg.fns`    |                  | Done     |
|                   | `fw/fwsetup.c`   | Done     |
|                   | `fw/genfile.c`   | Done     |
|                   | `fw/image.c`     | Done     |
| `fw/lexer.h`      | `fw/lexer.c`     | Done     |
|                   | `fw/loader.c`    | Done     |
|                   | `fw/mem.c`       | Done     |
|                   | `fw/object.c`    | Done     |
|                   | `fw/objectc.c`   | Done     |
|                   | `fw/pattern.c`   | Done     |
|                   | `fw/pool.c`      | Done     |
| `fw/pretok.h`     | `fw/pretok.c`    | N/A      |
|                   | `fw/printf.c`    | Done     |
| `fw/register.h`   | `fw/register.c`  | Done     |
|                   | `fw/resource.c`  | Done     |
|                   | `fw/resreg.c`    | Done     |
|                   | `fw/scratch.c`   | Done     |
|                   | `fw/scrstr.c`    | Done     |
| `fw/shortcut.h`   |                  | Done     |
|                   | `fw/sys_conf.c`  | Done     |
| `fw/timing.h`     |                  | Excluded |
|                   | `fw/token.c`     | Done     |
| `fw/tokenmap.h`   |                  | Done     |
|                   | `fw/tokenval.c`  | Done     |
|                   | `fw/tokentype.c` | Excluded |
| `fw/wincoff.h`    |                  | Done     |

## inc Status

| Header                             | Source          | Status   |
|------------------------------------|-----------------|----------|
| `inc/actor.h`                      |                 | Done     |
| `inc/angles.h`                     |                 | Done     |
| `inc/assoca_p.h`, `inc/assocarr.h` | `fw/assocarr.c` | Done     |
| `inc/brdiag.h`                     |                 | Done     |
| `inc/vector.h` -> `inc/brvector.h` |                 | Done     |                      
| `inc/brender.h`                    |                 | Done     |
| `inc/brerror.h`                    |                 | Done     | 
| `inc/brfile.h`                     |                 | Done     |
| `inc/brfont.h`                     |                 | Done     |
| `inc/brlimits.h`                   |                 | Done     |
| `inc/brmem.h`                      |                 | Done     |
| `inc/brv1db.h`                     |                 | Done     |
| `inc/camera.h`                     |                 | Done     |
| `inc/colour.h`                     |                 | Done     |
| `inc/compend.h`                    |                 | Done     |
| `inc/compiler.h`                   |                 |          |
| `inc/custsupt.h`                   |                 | Done     |
| `inc/dmyifix.h`                    |                 | Done     |
| `inc/fixed.h`                      |                 | Done     |
| `inc/fw_p.h`                       |                 | Done     |
| `inc/g386ifix.h`                   |                 | Excluded |
| `inc/light.h`                      |                 | Done     |
| `inc/material.h`                   |                 | Done     |
| `math_p`, `matrixXX.c`             |                 | Done     |
| `inc/matrix.h`                     |                 | Done     |
| `inc/model.h`                      |                 | Done     |
| `inc/order.h`                      |                 | Done     |
| `inc/pixelmap.h`,                  |                 | Done     |
| `inc/pm_p.h`                       |                 | Done     |
| `inc/pool.h`                       |                 | Done     |
| `inc/quat.h`                       |                 | Done     |
| `inc/render.h`                     |                 | Done     |
| `inc/scalar.h`                     |                 | Done     |
| `inc/syscn_p.h`                    | `fw/sys_conf.c` | Done     |
| `inc/token.h`                      |                 | Done     |
| `inc/transfrm.h`                   |                 | Done     |
| `inc/v1db_p.h`                     |                 |          |                  
| `inc/vecfns.h`                     |                 |          |
| `inc/wtcifix.h`                    |                 | Excluded |

## math Status
| Header           | Source            | Status |
|------------------|-------------------|--------|
|                  | `math/angles.c`   | Done   |
| `math/brmath.h`  |                   | Done   |
|                  | `math/fixed.c`    | Done   |        
| `math/math_ip.h` |                   | Done   |
|                  | `math/matrix4.c`  | Done   |
|                  | `math/matrix23.c` | Done   |
|                  | `math/matrix34.c` | Done   |
| `inc/math_p.h`   | `math/plane.c`    | Done   |
|                  | `math/quat.c`     | Done   |
|                  | `math/scalar.c`   | Done   |
|                  | `math/transfrm.c` | Done   |
| `math/vecifns.h` |                   | Done   |
|                  | `math/vector.c`   | Done   |

## std Status
| Header          | Source           | Status |
|-----------------|------------------|--------|
|                 | `std/brexcept.c` | Done   |
|                 | `std/logwrite.c` | Done   |
| `math/brmath.h` | `std/math.c`     | Done   |
|                 | `std/stddiag.c`  | Done   |
|                 | `std/stdfile.c`  | Done   |
|                 | `std/stdlib.c`   | Done   |
|                 | `std/stdmem.c`   | Done   |

## pixelmap Status
| Header             | Source                 | Status                                 |
|--------------------|------------------------|----------------------------------------|
| `inc/pixelmap.h`   |                        | Done                                   |
|                    | `pixelmap/fontptrs.c`  | Done                                   |
|                    | `pixelmap/genclip.c`   | Done                                   |
|                    | `pixelmap/gencopy.c`   | Done                                   |
|                    | `pixelmap/mipsupt.c`   | Done                                   |
|                    | `pixelmap/pixelmap.c`  | Done                                   |
| `pixelmap/pm_ip.h` |                        | Done, FPU loops removed                |
| `pixelmap/pm.h`    |                        | Done                                   |
|                    | `pixelmap/pmdisptch.c` | Done                                   |
|                    | `pixelmap/pmfile.c`    | Done                                   |
|                    | `pixelmap/pmgen.c`     | Done                                   |
|                    | `pixelmap/pmmem.c`     | Done, needs keyed copy implementation. |
|                    | `pixelmap/pmnull.c`    | Done                                   |
|                    | `pixelmap/pmsetup.c`   | Done                                   |
|                    | `pixelmap/quantize.c`  | Done                                   |
|                    | `pixelmap/scale.c`     | Done                                   |

## Post-update cleanups

* [x] `BRT_BUCKET_SORT_DEFERRED` -> `BRT_BUCKET_SORT`, `BRT_DIVERT`
* [x] Remove `BRT_COLOUR_R`, `BRT_COLOUR_G`, `BRT_COLOUR_B` light tokens/parts
* [x] Remove global ambience, ambient lights are now supported
    - [x] v1db.ambient_colour
    - [x] material ambient_colour
* [x] ~Renderer use non-interleaved data~
* [x] Create separate position buffer for mobile GPUs, should be easy now
* [x] BrBegin() and BrEnd() now return errors
* [x] Add ambient lighting
* [x] `BR_MAPU_DATA`/`BRT_UPDATE_DATA_B`
* [ ] Check actor reverse iteration (`**prev` -> `*prev`)
    - See why they did this
* [ ] #13
* [x] glrend - depth bias handling, not needed. Can reevaluate.
* [x] glrend - update blending logic, `3dfx_win/match.c`
* [ ] #14
* [x] glrend - separate specular, unsupported, no other drivers supported it either.
* [x] glrend - modulate alpha, unsupported. no other drivers supported it either.
* [x] glrend - handle BR_MATF_DISABLE_COLOUR_KEY properly
* [x] glrend - framebegin/end handling
* [x] glrend - focus loss handling
* [ ] #15
* [ ] viewpal - add

**Comment by crocguy0688** [comment]
Reopening until subtasks are done.
